### ISSUE TITLE
The unix package can't be install cause compiler can't find <pwd.h>

### ISSUE THREAD

**Issue by yangsiran** [GaloisInc/HaLVM#45] opened 2015-04-25 08:37 UTC
I am installing the `network-transport-tcp` package, which depends on `network-transport`, which in turns need the `unix` package. But when installing `unix`, with the -v3 option, the compiler said:
```
("/usr/bin/gcc",["/tmp/6136.c","-o","/tmp/6136","-D__GLASGOW_HASKELL__=708","-Dlinux_BUILD_OS=1","-Dx86_64_BUILD_ARCH=1","-Dx86_64_HOST_ARCH=1","-Idist/build/autogen","-Iinclude","-I.","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/time-1.4.2/include","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/bytestring-0.10.4.0/include","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/base-4.7.0.2/include","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/integer-gmp-0.5.1.0/include","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/include","-I/root/HaLVM/dist/lib/HaLVM-2.0.0/include/minlibc","-DHaLVM_TARGET_OS","-nostdinc","-DHaLVM_TARGET_OS","-nostdinc","-lrt","-lutil","-ldl","-lpthread","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/time-1.4.2","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/old-locale-1.0.0.6","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/bytestring-0.10.4.0","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/deepseq-1.3.0.2","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/array-0.5.0.0","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/base-4.7.0.2","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/integer-gmp-0.5.1.0","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/ghc-prim-0.3.1.0","-L/root/HaLVM/dist/lib/HaLVM-2.0.0/rts-1.0"])
/usr/bin/gcc returned ExitFailure 1 with error message:
In file included from /tmp/6136.c:1:0:
include/HsUnix.h:69:17: fatal error: pwd.h: No such file or directory
#include <pwd.h>
^
compilation terminated.
......
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: HsUnix.h
```
May I ask are there anyone meet the similar problem ?

**Comment by thumphries** [comment] 2015-04-25 09:00
This is by design. HaLVM's not Unix - it has no filesystem, no notion of a 'process', no 'users', etc. Anything with a hard dependency on `unix` won't build, because system libraries like `pwd.h` are not available.

However, I can't see any `unix` dependency for `network-transport` or `network-transport-tcp`. Is some other package in your program pulling it in?

**Comment by yangsiran** [comment] 2015-04-25 10:13
Thanks for your answer. I am trying to write program using the [Cloud Haskell](http://haskell-distributed.github.io) framework, or maybe try to port it onto HaLVM. More properly, `network-transport-tcp` depends on `network` which depends on `unix`. Maybe special `network-transport` layer need to be implemented for using Cloud Haskell on HaLVM.

**Comment by thumphries** [comment] 2015-04-25 18:49
Oh, I misread `network-transport-tcp.cabal`!

You will want to swap the `network` dep for `HaNS` and `network-hans`. Hopefully the package will then compile. `network-hans` uses the same API as `network`.

**Comment by thumphries** [comment] 2015-04-28 22:56
Closing this for now. If you successfully get `network-transport-tcp` to build, we'd love to hear about it.

**Closed by thumphries** 2015-04-28 22:56 UTC

**Comment by yangsiran** [comment] 2015-04-29 13:02
By simple replacing  `network` with `network-hans` and several rewriting of some unix dependency, the package seems to successfully build and link. But running a naive demo of `network-transport-tcp` did not get the correct result (it blocked in some TCP connection setup function). I am digging in to `network-transport-tcp` and related module to find out the reason.
